/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moirottoiec.GUI;

import java.sql.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import moirottoiec.BLL.StudentBLL;
import moirottoiec.DTO.Student;

/**
 *
 * @author Binh PC
 */
public class StudentManagementGUI extends javax.swing.JPanel {
    Student student;
    StudentBLL studentBLL;
    DefaultTableModel dtm;
    String tuKhoa = "";
    /**
     * Creates new form StudentManagementGUI
     */
    public StudentManagementGUI() {
        initComponents();
        student = new Student();
        studentBLL = new StudentBLL();
        loadStudentList();
    }
    
    public void search(){
        dtm.setRowCount(0);
        StudentBLL studentBLL = new StudentBLL();
        Vector<Student> arr = new Vector<Student>();
        arr = studentBLL.findStudent(tuKhoa);
        for(int i = 0; i < arr.size(); i++){
            Student em = arr.get(i);
            int PersonID = em.getPersonID();
            String LastName = em.getLastName();
            String FirstName = em.getFirstName();
            Date EnrollmentDate = em.getEnrollmentDate();
            Object[] row = {PersonID, LastName, FirstName , EnrollmentDate};
            dtm.addRow(row);
        }
    
    }
    
    public void loadStudentList(){
        dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        dtm.addColumn("PersonID");
        dtm.addColumn("Last Name");
        dtm.addColumn("First Name");
        dtm.addColumn("Enrollment Date");
        studentTable.setModel(dtm);
        StudentBLL lec = new StudentBLL();
        Vector<Student> arr = new Vector<Student>();
        //arr = lec.getAllLecturer();
        arr = lec.getAllStudent();
        System.out.println(arr);
        for(int i = 0; i < arr.size(); i++){
            Student em = arr.get(i);
            int PersonID = em.getPersonID();
            String LastName = em.getLastName();
            String FirstName = em.getFirstName();
            Date EnrollmentDate = em.getEnrollmentDate();
            Object[] row = {PersonID, LastName, FirstName , EnrollmentDate};
            dtm.addRow(row);
        } 
        addButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        findTextField9 = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        personIDTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        enrollmentDateTextField = new javax.swing.JTextField();

        jPanel11.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/GUI/img/teacher.png"))); // NOI18N
        jLabel14.setText("STUDENT MANAGEMENT");

        findTextField9.setText("Searching...");
        findTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findTextField9MouseClicked(evt);
            }
        });
        findTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTextField9ActionPerformed(evt);
            }
        });
        findTextField9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                findTextField9PropertyChange(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 0, 0));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/GUI/img/plus.png"))); // NOI18N
        addButton.setText("Add new");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonaddLecActionPerformed(evt);
            }
        });

        studentTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PersonID", "Last Name", "First Name", "Enrollment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentTable.setAutoscrolls(false);
        studentTable.setRowHeight(18);
        studentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studentTable);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 0, 0));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/GUI/img/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonaddLecActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 0, 0));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/GUI/img/refresh.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonaddLecActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 0, 0));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/GUI/img/refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("PersonID");

        personIDTextField.setEditable(false);
        personIDTextField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Enrollment Date");

        firstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        enrollmentDateTextField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(69, 69, 69)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(78, 78, 78)
                                .addComponent(personIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(enrollmentDateTextField)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addGap(96, 96, 96)
                                .addComponent(updateButton)
                                .addGap(91, 91, 91)
                                .addComponent(deleteButton)
                                .addGap(80, 80, 80)
                                .addComponent(refreshButton))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                    .addComponent(findTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(109, 109, 109)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap(3, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(searchButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enrollmentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findTextField9MouseClicked
        // TODO add your handling code here:
        findTextField9.setText("");
        
    }//GEN-LAST:event_findTextField9MouseClicked

    private void findTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findTextField9ActionPerformed

    private void findTextField9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_findTextField9PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_findTextField9PropertyChange

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        tuKhoa = findTextField9.getText();
        search();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void addButtonaddLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonaddLecActionPerformed
        // TODO add your handling code here:
        String lName = lastNameTextField.getText();
        String fName = firstNameTextField.getText();
        String hDate = enrollmentDateTextField.getText();

        if(lName.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ho!");
        }
        else if(fName.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên!");
        }
        else if(hDate.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày thuê!");
        }else{
            student.setLastName(lName);
            student.setFirstName(fName);
            student.setEnrollmentDate(Date.valueOf(enrollmentDateTextField.getText()));
            studentBLL.addStudent(student);
            JOptionPane.showMessageDialog(this, "Thêm giảng viên thành công!");
            loadStudentList();
            lastNameTextField.setText("");
            firstNameTextField.setText("");
            enrollmentDateTextField.setText("");
        }
    }//GEN-LAST:event_addButtonaddLecActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:
        studentBLL = new StudentBLL();
        int row = studentTable.getSelectedRow();
        student = studentBLL.getStudentByID((int) studentTable.getValueAt(row, 0));

        personIDTextField.setText(String.valueOf(student.getPersonID()));
        lastNameTextField.setText(student.getLastName());
        firstNameTextField.setText(student.getFirstName());
        enrollmentDateTextField.setText(String.valueOf(student.getEnrollmentDate()));
        addButton.setEnabled(false);
    }//GEN-LAST:event_studentTableMouseClicked

    private void deleteButtonaddLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonaddLecActionPerformed
        // TODO add your handling code here:
        StudentBLL stuBLL = new StudentBLL();
        int row = studentTable.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(StudentManagementGUI.this, "Vui long chon sinh vien can xoa!", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(StudentManagementGUI.this, "Ban chac chan muon xoa chu?");
            if(confirm == JOptionPane.YES_OPTION){
                int personID = (int) studentTable.getValueAt(row, 0);
                stuBLL.deleteStudent(personID);
                 personIDTextField.setText("");
                 lastNameTextField.setText("");
                 firstNameTextField.setText("");
                 enrollmentDateTextField.setText("");
                loadStudentList();
            }
        }
    }//GEN-LAST:event_deleteButtonaddLecActionPerformed

    private void updateButtonaddLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonaddLecActionPerformed
        // TODO add your handling code here:
        StudentBLL stuBLL = new StudentBLL();
        Student student = new Student();
        int row = studentTable.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(StudentManagementGUI.this, "Vui long chon sinh vien can sua!",  "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int personID = (int) studentTable.getValueAt(row, 0);

            student.setPersonID(personID);
            student.setLastName(lastNameTextField.getText());
            student.setFirstName(firstNameTextField.getText());
            student.setEnrollmentDate(Date.valueOf(enrollmentDateTextField.getText()));
            studentBLL.updateStudent(student);
            personIDTextField.setText("");
            lastNameTextField.setText("");
            firstNameTextField.setText("");
            enrollmentDateTextField.setText("");
            loadStudentList();
        }

    }//GEN-LAST:event_updateButtonaddLecActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        personIDTextField.setText("");
        lastNameTextField.setText("");
        firstNameTextField.setText("");
        enrollmentDateTextField.setText("");
        this.loadStudentList();
        findTextField9.setText("Searching...");
        
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField enrollmentDateTextField;
    private javax.swing.JTextField findTextField9;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField personIDTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
